INSERT INTO artist (artist_name, name, surname) VALUES
                                                    ('AC/DC', 'Malcolm', 'Young'),
                                                    ('AC/DC', 'Angus', 'Young'),
                                                    ('The Beatles', 'John', 'Lennon'),
                                                    ('The Beatles', 'Paul', 'McCartney'),
                                                    ('The Beatles', 'George', 'Harrison'),
                                                    ('The Beatles', 'Ringo', 'Starr'),
                                                    ('Queen', 'Freddie', 'Mercury'),
                                                    ('Queen', 'Brian', 'May'),
                                                    ('Queen', 'John', 'Deacon'),
                                                    ('Queen', 'Roger', 'Taylor'),
                                                    ('Michael Jackson', 'Michael', 'Jackson'),
                                                    ('Madonna', 'Madonna', 'Ciccone'),
                                                    ('Prince', 'Prince', 'Rogers Nelson'),
                                                    ('David Bowie', 'David', 'Bowie'),
                                                    ('Elvis Presley', 'Elvis', 'Presley'),
                                                    ('Led Zeppelin', 'Jimmy', 'Page'),
                                                    ('Led Zeppelin', 'Robert', 'Plant'),
                                                    ('Led Zeppelin', 'John', 'Bonham'),
                                                    ('Led Zeppelin', 'John Paul', 'Jones'),
                                                    ('Pink Floyd', 'David', 'Gilmour'),
                                                    ('Pink Floyd', 'Roger', 'Waters'),
                                                    ('Pink Floyd', 'Syd', 'Barrett'),
                                                    ('Nirvana', 'Kurt', 'Cobain'),
                                                    ('Nirvana', 'Krist', 'Novoselic'),
                                                    ('Nirvana', 'Dave', 'Grohl'),
                                                    ('Metallica', 'James', 'Hetfield'),
                                                    ('Metallica', 'Lars', 'Ulrich'),
                                                    ('Metallica', 'Kirk', 'Hammett'),
                                                    ('Metallica', 'Robert', 'Trujillo'),
                                                    ('The Rolling Stones', 'Mick', 'Jagger'),
                                                    ('The Rolling Stones', 'Keith', 'Richards'),
                                                    ('The Rolling Stones', 'Charlie', 'Watts'),
                                                    ('The Rolling Stones', 'Ronnie', 'Wood'),
                                                    ('U2', 'Bono', 'Vox'),
                                                    ('U2', 'The Edge', 'Evans'),
                                                    ('U2', 'Adam', 'Clayton'),
                                                    ('U2', 'Larry', 'Mullen Jr.'),
                                                    ('Pearl Jam', 'Eddie', 'Vedder'),
                                                    ('Pearl Jam', 'Stone', 'Gossard'),
                                                    ('Pearl Jam', 'Jeff', 'Ament'),
                                                    ('Pearl Jam', 'Mike', 'McCready'),
                                                    ('Green Day', 'Billie', 'Joe Armstrong'),
                                                    ('Green Day', 'Mike', 'Dirnt'),
                                                    ('Green Day', 'Tré', 'Cool'),
                                                    ('Radiohead', 'Thom', 'Yorke'),
                                                    ('Radiohead', 'Jonny', 'Greenwood'),
                                                    ('Radiohead', 'Colin', 'Greenwood'),
                                                    ('Radiohead', 'Philip', 'Selway'),
                                                    ('The Doors', 'Jim', 'Morrison'),
                                                    ('The Doors', 'Ray', 'Manzarek'),
                                                    ('The Doors', 'Robby', 'Krieger'),
                                                    ('The Doors', 'John', 'Densmore');

--dla tabeli Songs
INSERT INTO songs (title, artist, song_file) VALUES
                                                   ('Shape of You', 1, null),
                                                   ('Thinking Out Loud', 1, null),
                                                   ('Perfect', 1, null),
                                                   ('Photograph', 1, null),
                                                   ('Castle on the Hill', 1, null),
                                                   ('Someone Like You', 2, null),
                                                   ('Hello', 2, null),
                                                   ('Rolling in the Deep', 2, null),
                                                   ('Set Fire to the Rain', 2, null),
                                                   ('Skyfall', 2, null),
                                                   ('Thriller', 3, null),
                                                   ('Beat It', 3, null),
                                                   ('Billie Jean', 3, null),
                                                   ('Smooth Criminal', 3, null),
                                                   ('Black or White', 3, null),
                                                   ('Bohemian Rhapsody', 4, null),
                                                   ('We Will Rock You', 4, null),
                                                   ('Don''t Stop Me Now', 4, null),
                                                   ('Somebody to Love', 4, null),
                                                   ('Another One Bites the Dust', 4, null),
                                                   ('Livin'' on a Prayer', 5, null),
                                                   ('You Give Love a Bad Name', 5, null),
                                                   ('Wanted Dead or Alive', 5, null),
                                                   ('It''s My Life', 5, null),
                                                   ('Always', 5, null),
                                                   ('Stairway to Heaven', 6, null),
                                                   ('Whole Lotta Love', 6, null),
                                                   ('Immigrant Song', 6, null),
                                                   ('Black Dog', 6, null),
                                                   ('Kashmir', 6, null),
                                                   ('Smells Like Teen Spirit', 7, null),
                                                   ('Come as You Are', 7, null),
                                                   ('Lithium', 7, null),
                                                   ('Heart-Shaped Box', 7, null),
                                                   ('In Bloom', 7, null),
                                                   ('Californication', 8, null),
                                                   ('Under the Bridge', 8, null),
                                                   ('Scar Tissue', 8, null),
                                                   ('Give It Away', 8, null),
                                                   ('Can''t Stop', 8, null),
                                                   ('Lose Yourself', 9, null),
                                                   ('Without Me', 9, null),
                                                   ('The Real Slim Shady', 9, null),
                                                   ('Love the Way You Lie', 9, null),
                                                   ('Mockingbird', 9, null),
                                                   ('What''s My Name?', 10, null),
                                                   ('Umbrella', 10, null),
                                                   ('Diamonds', 10, null),
                                                   ('Work', 10, null),
                                                   ('We Found Love', 10, null);